# Generated by Django 5.1.7 on 2025-03-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_tags_scope_is_main_scope_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
    ]
